name: doc_reader
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  file_picker: ^8.0.0
  flutter_pdfview: ^1.3.2
  provider: ^6.1.2
  go_router: ^14.2.0
  path: ^1.9.0
  permission_handler: ^11.3.1
  intl: ^0.19.0
  share_plus: ^9.0.0
  flutter_file_view: ^2.2.1
  open_filex: ^4.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true